In [1]:
import pandas as pd

In [2]:
products_df = pd.read_csv("products.csv")
sales_df = pd.read_csv("sales.csv")

In [7]:
merged_df = pd.merge(products_df, sales_df, on="sku", how="left")
merged_df["quantity_sold"] = merged_df["quantity_sold"].fillna(0)

In [8]:
final_prices = []

for _, row in merged_df.iterrows():
    sku = row['sku']
    old_price = row['current_price']
    cost_price = row['cost_price']
    stock = row['stock']
    quantity_sold = row['quantity_sold']
    
    new_price = old_price

    if stock < 20 and quantity_sold > 30:
        new_price = old_price * 1.15
    elif stock > 200 and quantity_sold == 0:
        new_price = old_price * 0.7
    elif stock > 100 and quantity_sold < 20:
        new_price = old_price * 0.9

    min_price = cost_price * 1.2
    if new_price < min_price:
        new_price = min_price

    new_price = round(new_price, 2)
    
    final_prices.append({
        "sku": sku,
        "old_price": f"₹{round(old_price, 2)}",
        "new_price": f"₹{new_price}"
    })

In [9]:
output_df = pd.DataFrame(final_prices)
output_df.to_csv("updated_prices.csv", index=False)
output_df.head()  # Optional: preview

    sku old_price new_price
0  A123   ₹649.99    ₹600.0
1  B456    ₹699.0   ₹803.85
2  C789    ₹999.0    ₹699.3

In [10]:
pd.read_csv("updated_prices.csv")

    sku old_price new_price
0  A123   ₹649.99    ₹600.0
1  B456    ₹699.0   ₹803.85
2  C789    ₹999.0    ₹699.3